### ISSUE TITLE
Welcome to GitHub

### ISSUE THREAD

**Issue by paulvi** [sandipchitale/m2e-phasesandgoals#1]
Hi Sandip

Please update a little bit entry http://marketplace.eclipse.org/content/phases-and-goals
- [ ] Please include Maven into the name, e.g. "Maven Phases and Goals",
  so it is easier to find.
- [ ] there is typo in 

> May times you want to list the actual goals associated with phases of Mane lifecycle. 

Mane -> Maven

**Comment by sandipchitale** [comment]
Done.
